apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kzc7k6if6-python 
  janus-idp.io/tekton: kzc7k6if6-python
  backstage.io/kubernetes-id: kzc7k6if6-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kzc7k6if6-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml