apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kzc7k6if6-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kzc7k6if6-python 
  name: kzc7k6if6-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kzc7k6if6-python 
